Add Coffee Shop screen
coffee-map-vk-bootcamp/coffee-map pull request #8
Opened 2022-08-10 21:38 UTC by antigluten

- Добавил Coffee Shop Screen
- Добавил расширения для упрощения верстки
- Написал пока на MVC, так это быстрее с верстать, позже будет разделено на слои по VIPER
- Также на header осталось разместить оставшиеся элементы интерфейса (UIBarButtonItem, Label)

Экран: 

<img src="https://user-images.githubusercontent.com/53124465/184023747-2cd62964-4845-4f1c-8b34-cc35cb98a0ce.png" alt="iPhone 12" width="200"/>

2022-08-11 07:05 UTC, straivi requested changes

2022-08-11 07:05 UTC, straivi commented on CoffeeMap/Shop/Presenter/CoffeeShopDetailPresenter.swift
> +final class CoffeeShopDetailPresenter: DetailPresenterDescription {
суть презентера в том чтобы содержать в себе бизнес логику и ничего не знать о view. По этому должен быть `CoffeeShopDetailPresenter`  и делегат `CoffeeShopDetailPresenterDelegate`, и вот делегата уже реализует вью. К тому же вью не стоит передавать через инициализатор как зависимость в презентер

2022-08-11 07:05 UTC, straivi commented on CoffeeMap/Shop/View/CoffeeShopDetailCollectionViewCell.swift
> +        label.translatesAutoresizingMaskIntoConstraints = false
`translatesAutoresizingMaskIntoConstraints ` относится к констреинтам, лучше к ним перенести

2022-08-11 07:05 UTC, straivi commented on CoffeeMap/Shop/View/CoffeeShopDetailCollectionViewCell.swift
> +//        .init(width: (frame.size.width - 32 - 16 * 3) / 4, height: 164)
не стоит оставлять комменты в коде

2022-08-11 07:05 UTC, straivi commented on CoffeeMap/Shop/View/CoffeeShopDetailCollectionViewCell.swift
> +        .init(width: 95, height: 170)
а не можем отдать расчет размера автолейауту?

2022-08-11 07:05 UTC, straivi commented on CoffeeMap/Shop/View/DishCollectionViewCell.swift
> +        let image = UIImage(named: "coffee-test-1")
у нас есть AppImageNames чтобы не вставлять названия картинок строкой

2022-08-11 07:05 UTC, straivi commented on CoffeeMap/Shop/View/DishCollectionViewCell.swift
> +    lazy var blurView = UIVisualEffectView()
может тогда сразу инициализировать `UIBlurEffect ` а не `UIVisualEffectView `

2022-08-11 07:05 UTC, straivi commented on CoffeeMap/Shop/View/DishCollectionViewCell.swift
> +        priceLabel.text = nil
ещё картинку надо обнулять

2022-08-11 07:05 UTC, straivi commented on CoffeeMap/Shop/View/DishCollectionViewCell.swift
> +            blurView.leadingAnchor.constraint(equalTo: contentView.leadingAnchor),
а blurView это эффект для нажатия на ячейку коллекции?

2022-08-11 08:32 UTC, antigluten commented on CoffeeMap/Shop/View/DishCollectionViewCell.swift
> +            blurView.leadingAnchor.constraint(equalTo: contentView.leadingAnchor),
Это эффект размытия за картинкой

2022-08-11 11:20 UTC, atsed commented on CoffeeMap/Shop/View/CoffeeShopDetailCollectionViewCell.swift
> +        let padding: CGFloat = 16
horizontalPadding. Не крит

2022-08-11 11:20 UTC, atsed commented on CoffeeMap/Shop/View/CoffeeShopDetailCollectionViewCell.swift
> +        let spacing: CGFloat = 16
horizontalSpacing. Не крит

2022-08-11 11:20 UTC, atsed commented on CoffeeMap/Shop/View/CoffeeShopDetailCollectionViewCell.swift
> +        let offset = padding * 2 + spacing * numberOfRows
let offset = padding * 2 + spacing * (numberOfRows - 1)

2022-08-11 11:20 UTC, atsed commented on CoffeeMap/Shop/View/CoffeeShopDetailCollectionViewCell.swift
> +        let offset = padding * 2 + spacing * numberOfRows
Так как количество интервалов между ячейками на 1 меньше, чем количество ячеек

2022-08-11 11:20 UTC, atsed commented on CoffeeMap/Shop/View/CoffeeShopDetailHeaderView.swift
> +        addSubview(headerImageView)
Лучше не захламлять override init, а вынести в метод. Не крит

2022-08-11 11:20 UTC, atsed commented on CoffeeMap/Shop/View/CoffeeShopDetailCollectionViewCell.swift
> +    private lazy var collectionView = UICollectionView(frame: .zero, collectionViewLayout: UICollectionViewLayout())
private lazy var сoffeeShopDetailCollectionView. collectionView не совсем понятно. Не крит

2022-08-11 11:20 UTC, atsed commented on CoffeeMap/Shop/View/CoffeeShopViewController.swift
> +    lazy var collectionView: UICollectionView =  UICollectionView(frame: .zero, collectionViewLayout: UICollectionViewLayout())
**private** lazy var **сoffeeShopCollectionView**. Не крит

2022-08-11 11:20 UTC, atsed commented on CoffeeMap/Shop/View/DishCollectionViewCell.swift
> +    lazy var dishNameLabel: UILabel = {
private

2022-08-11 11:20 UTC, atsed commented on CoffeeMap/Shop/View/DishCollectionViewCell.swift
> +    lazy var priceLabel: UILabel = {
private

2022-08-11 11:20 UTC, atsed commented on CoffeeMap/Shop/View/DishCollectionViewCell.swift
> +    lazy var blurView: UIVisualEffectView = {
private

2022-08-11 11:20 UTC, atsed commented on CoffeeMap/Shop/View/DishCollectionViewCell.swift
> +    lazy var dishImageView = UIImageView()
private

2022-08-11 11:20 UTC, atsed commented on CoffeeMap/Shop/View/DishCollectionViewCell.swift
> +        contentView.addSubview(blurView)
Можно сделать так, не крит:
[blurView, dishNameLabel, priceLabel, dishImageView].forEach { contentView.addSubview($0)}

2022-08-12 13:02 UTC, antigluten commented
Текущий вариант + сделанный модуль на VIPER
<img src="https://user-images.githubusercontent.com/53124465/184359065-d927611e-c573-4dc5-9377-349bdb4e39a6.png" alt="iPhone 12" width="200"/>

2022-08-12 15:25 UTC, atsed commented on CoffeeMap/ShopDetail/CoffeeShopDetailScreenProtocols.swift
> +    func item(at index: Int) -> DishSection
Названия методов лучше делать в виде глаголов. Например, получить объекты getItem. Не крит

2022-08-12 15:25 UTC, atsed commented on CoffeeMap/ShopDetail/Views/CoffeeShopDetailHeaderView.swift
> +        NSLayoutConstraint.activate([
Верстку вынести в override func layoutSubviews()

2022-08-12 15:25 UTC, atsed commented on CoffeeMap/ShopDetail/Cells/DishCollectionViewCell.swift
> +        NSLayoutConstraint.activate([
Верстку вынести в override func layoutSubviews()

2022-08-12 15:25 UTC, atsed commented on CoffeeMap/ShopDetail/Cells/DishCollectionViewCell.swift
> +        NSLayoutConstraint.activate([
Верстку вынести в override func layoutSubviews()

2022-08-12 15:25 UTC, atsed commented on CoffeeMap/ShopDetail/Cells/DishCollectionViewCell.swift
> +        NSLayoutConstraint.activate([
Верстку вынести в override func layoutSubviews()

2022-08-12 15:25 UTC, atsed commented on CoffeeMap/ShopDetail/Cells/DishCollectionViewCell.swift
> +        NSLayoutConstraint.activate([
Верстку вынести в override func layoutSubviews()

2022-08-12 15:25 UTC, atsed commented on CoffeeMap/ShopDetail/Cells/CoffeeShopDetailCollectionViewCell.swift
> +        layoutSectionTitle()
Верстку вынести в override func layoutSubviews()

2022-08-12 15:55 UTC, atsed commented on CoffeeMap/ShopDetail/Cells/DishCollectionViewCell.swift
> +        let image = UIImage(named: AppImageNames.mockDishImage1)
В версте должна быть только верстка, нет смысла каждый раз пересоздавать и конфигурировать элементы

2022-08-12 16:02 UTC, atsed approved these changes

2022-08-12 16:04 UTC, merged